[package]
name = "nhdesigngen"
version = "0.1.0"
authors = ["Taylor C. Richberger <taywee@gmx.com>"]
edition = "2018"
description = "An Animal Crossing: New Horizons design generator"
readme = "README.md"
homepage = "https://gitlab.com/Taywee/nhdesigngen"
repository = "https://gitlab.com/Taywee/nhdesigngen"
license = "MIT"
keywords = ["games", "graphics"]
categories = ["games","multimedia::images", "multimedia"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
